########################### DEV ###########################
ssh-broker-dev|/home/ubuntu/AWS_KPs/DEV_App_Server.pem|ubuntu|192.168.10.25
ssh-dataeng|/home/ubuntu/AWS_KPs/DEV_DataEng.pem|ubuntu|192.168.10.38

########################### UAT ###########################
ssh-mis-uat|/home/ubuntu/AWS_KPs/UAT_MIS_Server.pem|ubuntu|192.168.20.8
ssh-esb-uat|/home/ubuntu/AWS_KPs/UAT_ESB_MQ.pem|ubuntu|192.168.20.31
ssh-uatdeploy|/home/ubuntu/AWS_KPs/UAT_Deployment.pem|ubuntu|192.168.20.57
ssh-commwkld-uat|/home/ubuntu/AWS_KPs/UAT_Comm_Workloads.pem|ubuntu|192.168.20.54
ssh-verdaccio-uat|/home/ubuntu/AWS_KPs/UAT_Verdaccio.pem|ubuntu|192.168.20.31
ssh-broker-uat-1|/home/ubuntu/AWS_KPs/UAT_Broker_Apps.pem|ubuntu|192.168.20.132
ssh-broker-uat-2|/home/ubuntu/AWS_KPs/UAT_Broker_Apps.pem|ubuntu|192.168.20.110
ssh-broker-uat-3|/home/ubuntu/AWS_KPs/UAT_Broker_Apps.pem|ubuntu|192.168.20.226
ssh-broker-uat-4|/home/ubuntu/AWS_KPs/UAT_Broker_Apps.pem|ubuntu|192.168.20.237
ssh-broker-uat-5|/home/ubuntu/AWS_KPs/UAT_Broker_Apps.pem|ubuntu|192.168.20.224
ssh-uat-mdb|/home/ubuntu/AWS_KPs/UAT_MongoDB.pem|ubuntu|192.168.20.35
ssh-esb-db-1|/home/ubuntu/AWS_KPs/UAT_ESB_DB.pem|ubuntu|192.168.20.243
ssh-ota-lb-uat|/home/ubuntu/AWS_KPs/UAT_OTA_LB.pem|ubuntu|192.168.20.255
ssh-uat-de|/home/ubuntu/AWS_KPs/UAT_DataEng.pem|ubuntu|192.168.20.66
ssh-esb-db-2|/home/ubuntu/AWS_KPs/UAT_ESB_DB.pem|ubuntu|192.168.20.43
ssh-ecom-db|/home/ubuntu/AWS_KPs/UAT_ECOM_DB.pem|ubuntu|192.168.20.17
ssh-dwh-db|/home/ubuntu/AWS_KPs/UAT_DWH_DB.pem|ubuntu|192.168.20.10

########################### PROD ###########################
ssh-volody|/home/ubuntu/AWS_KPs/PROD_Volody.pem|ubuntu|10.20.7.10
ssh-staff|/home/ubuntu/AWS_KPs/PROD_Staff_Portal.pem|ubuntu|10.20.7.125
ssh-proddeploy|/home/ubuntu/AWS_KPs/PROD_Deployment.pem|ubuntu|10.20.7.11
ssh-nessus|/home/ubuntu/AWS_KPs/PROD_Nessus.pem|ubuntu|10.20.7.115
ssh-avsec|/home/ubuntu/AWS_KPs/PROD_AVSEC.pem|ubuntu|10.20.6.196
ssh-www-redir|/home/ubuntu/AWS_KPs/PROD_WWW_Redir.pem|ubuntu|10.20.6.41
ssh-sysadmin|/home/ubuntu/AWS_KPs/PROD_SysAdmin.pem|ubuntu|10.20.6.180
ssh-sftp|/home/ubuntu/AWS_KPs/PROD_SFTP.pem|ubuntu|10.20.6.116
ssh-sabre|/home/ubuntu/AWS_KPs/PROD_MIS_Reporting.pem|ubuntu|10.20.6.51
ssh-esb-prod|/home/ubuntu/AWS_KPs/PROD_ESB_MQ.pem|ubuntu|10.20.6.136
ssh-rmsystems|/home/ubuntu/AWS_KPs/PROD_RM_Systems.pem|ubuntu|10.20.6.244
ssh-cae-amq|/home/ubuntu/AWS_KPs/PROD_ActiveMQ.pem|ubuntu|10.20.6.181
ssh-ironpdf|/home/ubuntu/AWS_KPs/PROD_IronPDF.pem|ubuntu|10.20.7.61
ssh-broker-preprod|/home/ubuntu/AWS_KPs/PROD_BL_AMI.pem|ubuntu|10.20.6.195
ssh-blami|/home/ubuntu/AWS_KPs/PROD_BLAMI.pem|ubuntu|10.20.6.112
ssh-rm-mdb|/home/ubuntu/AWS_KPs/PROD_DB_RM.pem|ubuntu|10.20.6.179
ssh-rtd-mdb|/home/ubuntu/AWS_KPs/PROD_MongoDB_DE.pem|ubuntu|10.20.6.153
ssh-ota-lb1-prod|/home/ubuntu/AWS_KPs/PROD_OTA_Broker.pem|ubuntu|10.20.12.16
ssh-ota-lb2-prod|/home/ubuntu/AWS_KPs/PROD_OTA_Broker.pem|ubuntu|10.20.12.94
ssh-ota-lb3-prod|/home/ubuntu/AWS_KPs/PROD_OTA_Broker.pem|ubuntu|10.20.12.78
ssh-kafka-ui|/home/ubuntu/AWS_KPs/PROD_Kafka_UI.pem|ubuntu|10.20.6.212
ssh-prod-deng|/home/ubuntu/AWS_KPs/PROD_DataEng.pem|ubuntu|10.20.6.5
